import Head from "next/head";
import NextLink from "next/link";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import cn from "classnames";
import MobileMenu from "./MobileMenu";

function NavItem({ href, text }) {
  const router = useRouter();
  const isActive = router.asPath === href;

  return (
    <NextLink href={href}>
      <a
        className={cn(
          isActive ? "font-semibold text-purple-700" : "font-normal text-purple-900",
          "hidden md:inline-block p-1 sm:px-3 text-purple-600 sm:py-2 rounded-lg hover:bg-purple-500 hover:text-white transition-all"
        )}
      >
        <span className="capsize">{text}</span>
      </a>
    </NextLink>
  );
}

export default function Container(props) {
  const [mounted, setMounted] = useState(false);
  useEffect(() => setMounted(true), []);

  const { children } = props;
  const router = useRouter();

  return (
    <div className="bg-my">
      <Head>
        <title>Shania Gracia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="robots" content="follow, index" />
      </Head>

      <header className="bg-my flex flex-col justify-center">
        <nav className="flex items-center justify-between w-full relative px-8 border-gray-200 mx-auto pt-8 pb-8 text-gray-900 bg-opacity-60">
          <div className="font-bold text-purple-700">SHNGRC</div>
          <div className="ml-[-0.60rem]">
            <MobileMenu />
            <NavItem href="/" text="Home" />
            <NavItem href="#" text="About" />
          </div>
        </nav>
      </header>

      <main className="justify-center">{children}</main>

      <footer className="flex flex-col justify-center justify-items-center p-8">
        <div className="flex flex-col justify-center items-start max-w-2xl mx-auto">
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className="">
              <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </div>
      </footer>
    </div>
  );
}
